"use client";
import React, { useState } from "react";
import { C, S, F } from '../../lib/theme.js';

export function SetRow({set,setNum,prev,exerciseType,onUpdate,onComplete}){
  const[ew,setEw]=useState(false);const[er,setEr]=useState(false);const[ed,setEd]=useState(false);const[eb,setEb]=useState(false);
  const inp={background:'transparent',border:'none',borderBottom:`2px solid ${C.accent}`,outline:'none',fontFamily:F.mono,fontSize:16,color:C.text,width:52,textAlign:'center',padding:'4px 0'};
  const cell={fontFamily:F.mono,fontSize:16,textAlign:'center',cursor:'pointer',padding:'5px',borderRadius:8,transition:'background .12s',minHeight:44,display:'flex',alignItems:'center',justifyContent:'center'};
  const checkBtn=<button onClick={onComplete} style={{width:44,height:44,borderRadius:12,background:C.elevated,border:`1.5px solid ${C.border}`,color:C.muted,fontSize:18,cursor:'pointer',display:'flex',alignItems:'center',justifyContent:'center',transition:'all .14s'}} onMouseEnter={e=>{e.currentTarget.style.background=C.green+'18';e.currentTarget.style.borderColor=C.green;e.currentTarget.style.color=C.green;}} onMouseLeave={e=>{e.currentTarget.style.background=C.elevated;e.currentTarget.style.borderColor=C.border;e.currentTarget.style.color=C.muted;}}>✓</button>;
  const prevFmt = prev ? (exerciseType==='timed' ? `${prev.duration||0}s` : exerciseType==='weighted' ? `${prev.weight||'BW'}×${prev.reps}` : `${prev.reps}`) : '-';
  const eType = exerciseType || 'weighted';

  if(eType==='timed'){
    const cols='28px 1fr 80px 44px';
    if(set.completed) return(<div style={{display:'grid',gridTemplateColumns:cols,gap:6,alignItems:'center',padding:'9px 4px',background:C.green+'14',borderRadius:10,marginBottom:5}}><span style={{fontFamily:F.mono,fontSize:11,color:C.muted,textAlign:'center'}}>{setNum}</span><span style={{fontFamily:F.mono,fontSize:11,color:C.muted}}>—</span><span style={{fontFamily:F.mono,fontSize:16,color:C.green,textAlign:'center',fontWeight:500}}>{set.duration}s</span><span style={{textAlign:'center',color:C.green,fontSize:18}}>✓</span></div>);
    return(<div style={{display:'grid',gridTemplateColumns:cols,gap:6,alignItems:'center',padding:'6px 4px',marginBottom:5}}><span style={{fontFamily:F.mono,fontSize:11,color:C.muted,textAlign:'center'}}>{setNum}</span><span style={{fontFamily:F.mono,fontSize:11,color:C.muted}}>{prevFmt}</span>{ed?<input autoFocus type="number" defaultValue={set.duration} style={inp} onBlur={e=>{onUpdate({duration:parseInt(e.target.value)||0});setEd(false);}} onKeyDown={e=>e.key==='Enter'&&e.target.blur()}/>:<div onClick={()=>setEd(true)} style={cell} onMouseEnter={e=>e.currentTarget.style.background=C.elevated} onMouseLeave={e=>e.currentTarget.style.background='transparent'}>{set.duration||0}s</div>}{checkBtn}</div>);
  }

  if(eType==='banded'){
    const cols='28px 1fr 60px 60px 44px';
    if(set.completed) return(<div style={{display:'grid',gridTemplateColumns:cols,gap:6,alignItems:'center',padding:'9px 4px',background:C.green+'14',borderRadius:10,marginBottom:5}}><span style={{fontFamily:F.mono,fontSize:11,color:C.muted,textAlign:'center'}}>{setNum}</span><span style={{fontFamily:F.mono,fontSize:11,color:C.muted}}>—</span><span style={{fontFamily:F.mono,fontSize:14,color:C.green,textAlign:'center',fontWeight:500}}>{set.band||'—'}</span><span style={{fontFamily:F.mono,fontSize:16,color:C.green,textAlign:'center',fontWeight:500}}>{set.reps}</span><span style={{textAlign:'center',color:C.green,fontSize:18}}>✓</span></div>);
    return(<div style={{display:'grid',gridTemplateColumns:cols,gap:6,alignItems:'center',padding:'6px 4px',marginBottom:5}}><span style={{fontFamily:F.mono,fontSize:11,color:C.muted,textAlign:'center'}}>{setNum}</span><span style={{fontFamily:F.mono,fontSize:11,color:C.muted}}>{prevFmt}</span>{eb?<select autoFocus defaultValue={set.band||'medium'} style={{...inp,width:60,borderBottom:`2px solid ${C.accent}`}} onChange={e=>{onUpdate({band:e.target.value});setEb(false);}} onBlur={()=>setEb(false)}><option value="light">Light</option><option value="medium">Med</option><option value="heavy">Heavy</option></select>:<div onClick={()=>setEb(true)} style={{...cell,fontSize:14}} onMouseEnter={e=>e.currentTarget.style.background=C.elevated} onMouseLeave={e=>e.currentTarget.style.background='transparent'}>{set.band||'Med'}</div>}{er?<input autoFocus type="number" defaultValue={set.reps} style={inp} onBlur={e=>{onUpdate({reps:parseInt(e.target.value)||0});setEr(false);}} onKeyDown={e=>e.key==='Enter'&&e.target.blur()}/>:<div onClick={()=>setEr(true)} style={cell} onMouseEnter={e=>e.currentTarget.style.background=C.elevated} onMouseLeave={e=>e.currentTarget.style.background='transparent'}>{set.reps}</div>}{checkBtn}</div>);
  }

  if(eType==='bodyweight'||eType==='cardio-drill'){
    const cols='28px 1fr 80px 44px';
    if(set.completed) return(<div style={{display:'grid',gridTemplateColumns:cols,gap:6,alignItems:'center',padding:'9px 4px',background:C.green+'14',borderRadius:10,marginBottom:5}}><span style={{fontFamily:F.mono,fontSize:11,color:C.muted,textAlign:'center'}}>{setNum}</span><span style={{fontFamily:F.mono,fontSize:11,color:C.muted}}>—</span><span style={{fontFamily:F.mono,fontSize:16,color:C.green,textAlign:'center',fontWeight:500}}>{set.reps} reps</span><span style={{textAlign:'center',color:C.green,fontSize:18}}>✓</span></div>);
    return(<div style={{display:'grid',gridTemplateColumns:cols,gap:6,alignItems:'center',padding:'6px 4px',marginBottom:5}}><span style={{fontFamily:F.mono,fontSize:11,color:C.muted,textAlign:'center'}}>{setNum}</span><span style={{fontFamily:F.mono,fontSize:11,color:C.muted}}>{prevFmt}</span>{er?<input autoFocus type="number" defaultValue={set.reps} style={inp} onBlur={e=>{onUpdate({reps:parseInt(e.target.value)||0});setEr(false);}} onKeyDown={e=>e.key==='Enter'&&e.target.blur()}/>:<div onClick={()=>setEr(true)} style={cell} onMouseEnter={e=>e.currentTarget.style.background=C.elevated} onMouseLeave={e=>e.currentTarget.style.background='transparent'}>{set.reps} reps</div>}{checkBtn}</div>);
  }

  // Default: weighted
  const cols='28px 1fr 60px 60px 44px';
  if(set.completed) return(<div style={{display:'grid',gridTemplateColumns:cols,gap:6,alignItems:'center',padding:'9px 4px',background:C.green+'14',borderRadius:10,marginBottom:5}}><span style={{fontFamily:F.mono,fontSize:11,color:C.muted,textAlign:'center'}}>{setNum}</span><span style={{fontFamily:F.mono,fontSize:11,color:C.muted}}>—</span><span style={{fontFamily:F.mono,fontSize:16,color:C.green,textAlign:'center',fontWeight:500}}>{set.weight||'BW'}</span><span style={{fontFamily:F.mono,fontSize:16,color:C.green,textAlign:'center',fontWeight:500}}>{set.reps}</span><span style={{textAlign:'center',color:C.green,fontSize:18}}>✓</span></div>);
  return(<div style={{display:'grid',gridTemplateColumns:cols,gap:6,alignItems:'center',padding:'6px 4px',marginBottom:5}}><span style={{fontFamily:F.mono,fontSize:11,color:C.muted,textAlign:'center'}}>{setNum}</span><span style={{fontFamily:F.mono,fontSize:11,color:C.muted}}>{prevFmt}</span>{ew?<input autoFocus type="number" defaultValue={set.weight} style={inp} onBlur={e=>{onUpdate({weight:parseFloat(e.target.value)||0});setEw(false);}} onKeyDown={e=>e.key==='Enter'&&e.target.blur()}/>:<div onClick={()=>setEw(true)} style={{...cell,color:set.weight?C.text:C.muted}} onMouseEnter={e=>e.currentTarget.style.background=C.elevated} onMouseLeave={e=>e.currentTarget.style.background='transparent'}>{set.weight||'BW'}</div>}{er?<input autoFocus type="number" defaultValue={set.reps} style={inp} onBlur={e=>{onUpdate({reps:parseInt(e.target.value)||0});setEr(false);}} onKeyDown={e=>e.key==='Enter'&&e.target.blur()}/>:<div onClick={()=>setEr(true)} style={cell} onMouseEnter={e=>e.currentTarget.style.background=C.elevated} onMouseLeave={e=>e.currentTarget.style.background='transparent'}>{set.reps}</div>}{checkBtn}</div>);
}
