import { exSlug } from './utils.js';

export const EXERCISE_DB = [
  // ─── Chest ───
  {name:'Bench Press (Barbell)',bodyPart:'Chest',category:'Barbell',exerciseType:'weighted'},
  {name:'Bench Press (Dumbbell)',bodyPart:'Chest',category:'Dumbbell',exerciseType:'weighted'},
  {name:'Incline Bench Press (Barbell)',bodyPart:'Chest',category:'Barbell',exerciseType:'weighted'},
  {name:'Incline Bench Press (Dumbbell)',bodyPart:'Chest',category:'Dumbbell',exerciseType:'weighted'},
  {name:'Decline Bench Press (Barbell)',bodyPart:'Chest',category:'Barbell',exerciseType:'weighted'},
  {name:'Decline Bench Press (Dumbbell)',bodyPart:'Chest',category:'Dumbbell',exerciseType:'weighted'},
  {name:'Chest Fly (Dumbbell)',bodyPart:'Chest',category:'Dumbbell',exerciseType:'weighted'},
  {name:'Chest Fly (Cable)',bodyPart:'Chest',category:'Cable',exerciseType:'weighted'},
  {name:'Chest Fly (Machine)',bodyPart:'Chest',category:'Machine',exerciseType:'weighted'},
  {name:'Push Up',bodyPart:'Chest',category:'Bodyweight',exerciseType:'bodyweight'},
  {name:'Diamond Push Up',bodyPart:'Chest',category:'Bodyweight',exerciseType:'bodyweight'},
  {name:'Chest Dip',bodyPart:'Chest',category:'Bodyweight',exerciseType:'bodyweight'},
  {name:'Chest Press (Machine)',bodyPart:'Chest',category:'Machine',exerciseType:'weighted'},
  {name:'Around the World',bodyPart:'Chest',category:'Dumbbell',exerciseType:'weighted'},
  // ─── Back ───
  {name:'Deadlift (Barbell)',bodyPart:'Back',category:'Barbell',exerciseType:'weighted'},
  {name:'Romanian Deadlift (Barbell)',bodyPart:'Back',category:'Barbell',exerciseType:'weighted'},
  {name:'Romanian Deadlift (Dumbbell)',bodyPart:'Back',category:'Dumbbell',exerciseType:'weighted'},
  {name:'Bent Over Row (Barbell)',bodyPart:'Back',category:'Barbell',exerciseType:'weighted'},
  {name:'Bent Over Row (Dumbbell)',bodyPart:'Back',category:'Dumbbell',exerciseType:'weighted'},
  {name:'T-Bar Row',bodyPart:'Back',category:'Barbell',exerciseType:'weighted'},
  {name:'Seated Row (Cable)',bodyPart:'Back',category:'Cable',exerciseType:'weighted'},
  {name:'Seated Row (Machine)',bodyPart:'Back',category:'Machine',exerciseType:'weighted'},
  {name:'Lat Pulldown (Cable)',bodyPart:'Back',category:'Cable',exerciseType:'weighted'},
  {name:'Lat Pulldown (Machine)',bodyPart:'Back',category:'Machine',exerciseType:'weighted'},
  {name:'Pull Up',bodyPart:'Back',category:'Bodyweight',exerciseType:'bodyweight'},
  {name:'Chin Up',bodyPart:'Back',category:'Bodyweight',exerciseType:'bodyweight'},
  {name:'Inverted Row',bodyPart:'Back',category:'Bodyweight',exerciseType:'bodyweight'},
  {name:'Back Extension',bodyPart:'Back',category:'Bodyweight',exerciseType:'bodyweight'},
  {name:'Back Extension (Machine)',bodyPart:'Back',category:'Machine',exerciseType:'weighted'},
  {name:'Good Morning (Barbell)',bodyPart:'Back',category:'Barbell',exerciseType:'weighted'},
  {name:'Single Arm Row (Dumbbell)',bodyPart:'Back',category:'Dumbbell',exerciseType:'weighted'},
  {name:'Face Pull (Cable)',bodyPart:'Back',category:'Cable',exerciseType:'weighted'},
  {name:'Face Pull (Band)',bodyPart:'Back',category:'Band',exerciseType:'banded'},
  {name:'Rack Pull (Barbell)',bodyPart:'Back',category:'Barbell',exerciseType:'weighted'},
  {name:'Pull Apart (Band)',bodyPart:'Back',category:'Band',exerciseType:'banded'},
  // ─── Shoulders ───
  {name:'Overhead Press (Barbell)',bodyPart:'Shoulders',category:'Barbell',exerciseType:'weighted'},
  {name:'Overhead Press (Dumbbell)',bodyPart:'Shoulders',category:'Dumbbell',exerciseType:'weighted'},
  {name:'Arnold Press (Dumbbell)',bodyPart:'Shoulders',category:'Dumbbell',exerciseType:'weighted'},
  {name:'Lateral Raise (Dumbbell)',bodyPart:'Shoulders',category:'Dumbbell',exerciseType:'weighted'},
  {name:'Lateral Raise (Cable)',bodyPart:'Shoulders',category:'Cable',exerciseType:'weighted'},
  {name:'Lateral Raise (Band)',bodyPart:'Shoulders',category:'Band',exerciseType:'banded'},
  {name:'Front Raise (Dumbbell)',bodyPart:'Shoulders',category:'Dumbbell',exerciseType:'weighted'},
  {name:'Front Raise (Barbell)',bodyPart:'Shoulders',category:'Barbell',exerciseType:'weighted'},
  {name:'Reverse Fly (Dumbbell)',bodyPart:'Shoulders',category:'Dumbbell',exerciseType:'weighted'},
  {name:'Reverse Fly (Cable)',bodyPart:'Shoulders',category:'Cable',exerciseType:'weighted'},
  {name:'Upright Row (Barbell)',bodyPart:'Shoulders',category:'Barbell',exerciseType:'weighted'},
  {name:'Upright Row (Dumbbell)',bodyPart:'Shoulders',category:'Dumbbell',exerciseType:'weighted'},
  {name:'Shoulder Press (Machine)',bodyPart:'Shoulders',category:'Machine',exerciseType:'weighted'},
  {name:'Pike Push Up',bodyPart:'Shoulders',category:'Bodyweight',exerciseType:'bodyweight'},
  {name:'Handstand Push Up',bodyPart:'Shoulders',category:'Bodyweight',exerciseType:'bodyweight'},
  {name:'Shrug (Barbell)',bodyPart:'Shoulders',category:'Barbell',exerciseType:'weighted'},
  {name:'Shrug (Dumbbell)',bodyPart:'Shoulders',category:'Dumbbell',exerciseType:'weighted'},
  // ─── Biceps ───
  {name:'Bicep Curl (Barbell)',bodyPart:'Biceps',category:'Barbell',exerciseType:'weighted'},
  {name:'Bicep Curl (Dumbbell)',bodyPart:'Biceps',category:'Dumbbell',exerciseType:'weighted'},
  {name:'Bicep Curl (Cable)',bodyPart:'Biceps',category:'Cable',exerciseType:'weighted'},
  {name:'Bicep Curl (Band)',bodyPart:'Biceps',category:'Band',exerciseType:'banded'},
  {name:'Hammer Curl (Dumbbell)',bodyPart:'Biceps',category:'Dumbbell',exerciseType:'weighted'},
  {name:'Preacher Curl (Barbell)',bodyPart:'Biceps',category:'Barbell',exerciseType:'weighted'},
  {name:'Preacher Curl (Dumbbell)',bodyPart:'Biceps',category:'Dumbbell',exerciseType:'weighted'},
  {name:'Preacher Curl (Machine)',bodyPart:'Biceps',category:'Machine',exerciseType:'weighted'},
  {name:'Concentration Curl (Dumbbell)',bodyPart:'Biceps',category:'Dumbbell',exerciseType:'weighted'},
  {name:'Incline Curl (Dumbbell)',bodyPart:'Biceps',category:'Dumbbell',exerciseType:'weighted'},
  {name:'Spider Curl (Dumbbell)',bodyPart:'Biceps',category:'Dumbbell',exerciseType:'weighted'},
  {name:'EZ-Bar Curl',bodyPart:'Biceps',category:'Barbell',exerciseType:'weighted'},
  // ─── Triceps ───
  {name:'Triceps Extension (Dumbbell)',bodyPart:'Triceps',category:'Dumbbell',exerciseType:'weighted'},
  {name:'Triceps Extension (Cable)',bodyPart:'Triceps',category:'Cable',exerciseType:'weighted'},
  {name:'Triceps Extension (Barbell)',bodyPart:'Triceps',category:'Barbell',exerciseType:'weighted'},
  {name:'Triceps Pushdown (Cable)',bodyPart:'Triceps',category:'Cable',exerciseType:'weighted'},
  {name:'Triceps Dip',bodyPart:'Triceps',category:'Bodyweight',exerciseType:'bodyweight'},
  {name:'Skull Crusher (Barbell)',bodyPart:'Triceps',category:'Barbell',exerciseType:'weighted'},
  {name:'Skull Crusher (Dumbbell)',bodyPart:'Triceps',category:'Dumbbell',exerciseType:'weighted'},
  {name:'Close Grip Bench Press (Barbell)',bodyPart:'Triceps',category:'Barbell',exerciseType:'weighted'},
  {name:'Kickback (Dumbbell)',bodyPart:'Triceps',category:'Dumbbell',exerciseType:'weighted'},
  {name:'Kickback (Cable)',bodyPart:'Triceps',category:'Cable',exerciseType:'weighted'},
  // ─── Core ───
  {name:'Ab Wheel',bodyPart:'Core',category:'Other',exerciseType:'bodyweight'},
  {name:'Crunch',bodyPart:'Core',category:'Bodyweight',exerciseType:'bodyweight'},
  {name:'Bicycle Crunch',bodyPart:'Core',category:'Bodyweight',exerciseType:'bodyweight'},
  {name:'Hanging Leg Raise',bodyPart:'Core',category:'Bodyweight',exerciseType:'bodyweight'},
  {name:'Lying Leg Raise',bodyPart:'Core',category:'Bodyweight',exerciseType:'bodyweight'},
  {name:'Plank',bodyPart:'Core',category:'Bodyweight',exerciseType:'timed'},
  {name:'Side Plank',bodyPart:'Core',category:'Bodyweight',exerciseType:'timed'},
  {name:'Russian Twist',bodyPart:'Core',category:'Bodyweight',exerciseType:'bodyweight'},
  {name:'Russian Twist (Dumbbell)',bodyPart:'Core',category:'Dumbbell',exerciseType:'weighted'},
  {name:'Cable Woodchop',bodyPart:'Core',category:'Cable',exerciseType:'weighted'},
  {name:'Pallof Press (Cable)',bodyPart:'Core',category:'Cable',exerciseType:'weighted'},
  {name:'Pallof Press (Band)',bodyPart:'Core',category:'Band',exerciseType:'banded'},
  {name:'Dead Bug',bodyPart:'Core',category:'Bodyweight',exerciseType:'bodyweight'},
  {name:'Mountain Climber',bodyPart:'Core',category:'Bodyweight',exerciseType:'cardio-drill'},
  {name:'Sit Up',bodyPart:'Core',category:'Bodyweight',exerciseType:'bodyweight'},
  {name:'V-Up',bodyPart:'Core',category:'Bodyweight',exerciseType:'bodyweight'},
  {name:'Hollow Body Hold',bodyPart:'Core',category:'Bodyweight',exerciseType:'timed'},
  // ─── Quads ───
  {name:'Squat (Barbell)',bodyPart:'Quads',category:'Barbell',exerciseType:'weighted'},
  {name:'Front Squat (Barbell)',bodyPart:'Quads',category:'Barbell',exerciseType:'weighted'},
  {name:'Goblet Squat (Dumbbell)',bodyPart:'Quads',category:'Dumbbell',exerciseType:'weighted'},
  {name:'Goblet Squat (Kettlebell)',bodyPart:'Quads',category:'Kettlebell',exerciseType:'weighted'},
  {name:'Leg Press',bodyPart:'Quads',category:'Machine',exerciseType:'weighted'},
  {name:'Leg Extension (Machine)',bodyPart:'Quads',category:'Machine',exerciseType:'weighted'},
  {name:'Hack Squat (Machine)',bodyPart:'Quads',category:'Machine',exerciseType:'weighted'},
  {name:'Bulgarian Split Squat (Dumbbell)',bodyPart:'Quads',category:'Dumbbell',exerciseType:'weighted'},
  {name:'Lunge (Dumbbell)',bodyPart:'Quads',category:'Dumbbell',exerciseType:'weighted'},
  {name:'Lunge (Barbell)',bodyPart:'Quads',category:'Barbell',exerciseType:'weighted'},
  {name:'Walking Lunge (Dumbbell)',bodyPart:'Quads',category:'Dumbbell',exerciseType:'weighted'},
  {name:'Step Up',bodyPart:'Quads',category:'Bodyweight',exerciseType:'bodyweight'},
  {name:'Step Up (Dumbbell)',bodyPart:'Quads',category:'Dumbbell',exerciseType:'weighted'},
  {name:'Pistol Squat',bodyPart:'Quads',category:'Bodyweight',exerciseType:'bodyweight'},
  {name:'Wall Sit',bodyPart:'Quads',category:'Bodyweight',exerciseType:'timed'},
  {name:'Sissy Squat',bodyPart:'Quads',category:'Bodyweight',exerciseType:'bodyweight'},
  {name:'Air Squat',bodyPart:'Quads',category:'Bodyweight',exerciseType:'bodyweight'},
  // ─── Hamstrings ───
  {name:'Leg Curl (Machine)',bodyPart:'Hamstrings',category:'Machine',exerciseType:'weighted'},
  {name:'Seated Leg Curl (Machine)',bodyPart:'Hamstrings',category:'Machine',exerciseType:'weighted'},
  {name:'Nordic Curl',bodyPart:'Hamstrings',category:'Bodyweight',exerciseType:'bodyweight'},
  {name:'Stiff Leg Deadlift (Barbell)',bodyPart:'Hamstrings',category:'Barbell',exerciseType:'weighted'},
  {name:'Stiff Leg Deadlift (Dumbbell)',bodyPart:'Hamstrings',category:'Dumbbell',exerciseType:'weighted'},
  {name:'Glute Ham Raise',bodyPart:'Hamstrings',category:'Bodyweight',exerciseType:'bodyweight'},
  {name:'Single Leg Deadlift (Dumbbell)',bodyPart:'Hamstrings',category:'Dumbbell',exerciseType:'weighted'},
  {name:'Single Leg Deadlift (Kettlebell)',bodyPart:'Hamstrings',category:'Kettlebell',exerciseType:'weighted'},
  // ─── Glutes ───
  {name:'Hip Thrust (Barbell)',bodyPart:'Glutes',category:'Barbell',exerciseType:'weighted'},
  {name:'Hip Thrust (Dumbbell)',bodyPart:'Glutes',category:'Dumbbell',exerciseType:'weighted'},
  {name:'Hip Thrust (Machine)',bodyPart:'Glutes',category:'Machine',exerciseType:'weighted'},
  {name:'Glute Bridge',bodyPart:'Glutes',category:'Bodyweight',exerciseType:'bodyweight'},
  {name:'Glute Bridge (Barbell)',bodyPart:'Glutes',category:'Barbell',exerciseType:'weighted'},
  {name:'Cable Pull Through',bodyPart:'Glutes',category:'Cable',exerciseType:'weighted'},
  {name:'Banded Walk',bodyPart:'Glutes',category:'Band',exerciseType:'banded'},
  {name:'Clamshell (Band)',bodyPart:'Glutes',category:'Band',exerciseType:'banded'},
  {name:'Donkey Kick',bodyPart:'Glutes',category:'Bodyweight',exerciseType:'bodyweight'},
  {name:'Fire Hydrant',bodyPart:'Glutes',category:'Bodyweight',exerciseType:'bodyweight'},
  {name:'Kickback (Cable Glute)',bodyPart:'Glutes',category:'Cable',exerciseType:'weighted'},
  // ─── Calves ───
  {name:'Standing Calf Raise (Machine)',bodyPart:'Calves',category:'Machine',exerciseType:'weighted'},
  {name:'Standing Calf Raise (Dumbbell)',bodyPart:'Calves',category:'Dumbbell',exerciseType:'weighted'},
  {name:'Standing Calf Raise (Barbell)',bodyPart:'Calves',category:'Barbell',exerciseType:'weighted'},
  {name:'Seated Calf Raise (Machine)',bodyPart:'Calves',category:'Machine',exerciseType:'weighted'},
  {name:'Calf Raise (Bodyweight)',bodyPart:'Calves',category:'Bodyweight',exerciseType:'bodyweight'},
  // ─── Full Body ───
  {name:'Clean (Barbell)',bodyPart:'Full Body',category:'Barbell',exerciseType:'weighted'},
  {name:'Clean and Jerk (Barbell)',bodyPart:'Full Body',category:'Barbell',exerciseType:'weighted'},
  {name:'Snatch (Barbell)',bodyPart:'Full Body',category:'Barbell',exerciseType:'weighted'},
  {name:'Power Clean (Barbell)',bodyPart:'Full Body',category:'Barbell',exerciseType:'weighted'},
  {name:'Thruster (Barbell)',bodyPart:'Full Body',category:'Barbell',exerciseType:'weighted'},
  {name:'Thruster (Dumbbell)',bodyPart:'Full Body',category:'Dumbbell',exerciseType:'weighted'},
  {name:'Kettlebell Swing',bodyPart:'Full Body',category:'Kettlebell',exerciseType:'weighted'},
  {name:'Turkish Get Up (Kettlebell)',bodyPart:'Full Body',category:'Kettlebell',exerciseType:'weighted'},
  {name:'Burpee',bodyPart:'Full Body',category:'Bodyweight',exerciseType:'cardio-drill'},
  {name:'Ball Slams',bodyPart:'Full Body',category:'Other',exerciseType:'weighted'},
  {name:'Battle Ropes',bodyPart:'Full Body',category:'Other',exerciseType:'timed'},
  {name:'Farmer Walk (Dumbbell)',bodyPart:'Full Body',category:'Dumbbell',exerciseType:'timed'},
  {name:'Farmer Walk (Kettlebell)',bodyPart:'Full Body',category:'Kettlebell',exerciseType:'timed'},
  {name:'Man Maker (Dumbbell)',bodyPart:'Full Body',category:'Dumbbell',exerciseType:'weighted'},
  {name:'Bear Crawl',bodyPart:'Full Body',category:'Bodyweight',exerciseType:'timed'},
  {name:'Box Jump',bodyPart:'Full Body',category:'Bodyweight',exerciseType:'bodyweight'},
  {name:'Jump Squat',bodyPart:'Full Body',category:'Bodyweight',exerciseType:'bodyweight'},
  {name:'High Knees',bodyPart:'Full Body',category:'Bodyweight',exerciseType:'cardio-drill'},
  {name:'Jump Rope',bodyPart:'Full Body',category:'Other',exerciseType:'timed'},
  {name:'Dead Hang',bodyPart:'Full Body',category:'Bodyweight',exerciseType:'timed'},
];

export const getExerciseDB = (customExercises) => {
  const all = [...EXERCISE_DB, ...(customExercises||[])];
  const seen = new Set();
  return all.filter(e => {const k = exSlug(e.name); if(seen.has(k)) return false; seen.add(k); return true;});
};

export const lookupExercise = (slug, customExercises) => {
  return EXERCISE_DB.find(e => exSlug(e.name) === slug) || (customExercises||[]).find(e => exSlug(e.name) === slug) || null;
};
