-- 008_exercise_catalog_expansion.sql
-- Expands the exercise catalog from 58 → ~227 entries, filling in the
-- Kettlebell and Band categories (which the library UI already filters on
-- but had no rows for), adding common variations across all body parts,
-- and deepening coverage of bodyweight / machine / cable work.
--
-- Slugs picked to avoid any conflict with 007_exercise_catalog.sql.
-- Muscle strings stay lowercase to match the conventions in the existing
-- rows ('lats', 'triceps', 'quads', 'glutes', etc.).

INSERT INTO exercises (slug, name, body_part, category, exercise_type, primary_muscles, sort_order) VALUES
-- Back (continuing 113+)
('trap-bar-deadlift',           'Trap Bar Deadlift',           'Back',      'Barbell',    'weighted',   ARRAY['back','hamstrings','glutes'], 113),
('stiff-leg-deadlift',          'Stiff-Leg Deadlift',          'Back',      'Barbell',    'weighted',   ARRAY['hamstrings','lower back'], 114),
('rack-pull',                    'Rack Pull',                   'Back',      'Barbell',    'weighted',   ARRAY['back','traps'], 115),
('deficit-deadlift',             'Deficit Deadlift',            'Back',      'Barbell',    'weighted',   ARRAY['back','hamstrings','glutes'], 116),
('dumbbell-row',                 'Dumbbell Row',                'Back',      'Dumbbell',   'weighted',   ARRAY['lats','upper back'], 117),
('single-arm-dumbbell-row',      'Single-Arm Dumbbell Row',     'Back',      'Dumbbell',   'weighted',   ARRAY['lats','upper back'], 118),
('chest-supported-row',          'Chest-Supported Row',         'Back',      'Dumbbell',   'weighted',   ARRAY['lats','rear delts'], 119),
('meadows-row',                  'Meadows Row',                 'Back',      'Barbell',    'weighted',   ARRAY['lats','upper back'], 120),
('inverted-row',                 'Inverted Row',                'Back',      'Bodyweight', 'bodyweight', ARRAY['lats','upper back'], 121),
('wide-grip-pull-up',            'Wide-Grip Pull-Up',           'Back',      'Bodyweight', 'bodyweight', ARRAY['lats'], 122),
('neutral-grip-pull-up',         'Neutral-Grip Pull-Up',        'Back',      'Bodyweight', 'bodyweight', ARRAY['lats','biceps'], 123),
('assisted-pull-up',             'Assisted Pull-Up',            'Back',      'Machine',    'weighted',   ARRAY['lats','biceps'], 124),
('straight-arm-pulldown',        'Straight-Arm Pulldown',       'Back',      'Cable',      'weighted',   ARRAY['lats'], 125),
('single-arm-cable-row',         'Single-Arm Cable Row',        'Back',      'Cable',      'weighted',   ARRAY['lats','upper back'], 126),
('back-extension',               'Back Extension',              'Back',      'Machine',    'bodyweight', ARRAY['lower back','glutes'], 127),
('superman',                     'Superman',                    'Back',      'Bodyweight', 'bodyweight', ARRAY['lower back','glutes'], 128),
('banded-row',                   'Banded Row',                  'Back',      'Band',       'banded',     ARRAY['lats','upper back'], 129),
('banded-pull-apart',            'Banded Pull-Apart',           'Back',      'Band',       'banded',     ARRAY['rear delts','upper back'], 130),
('banded-face-pull',             'Banded Face Pull',            'Back',      'Band',       'banded',     ARRAY['rear delts','upper back'], 131),
('banded-lat-pulldown',          'Banded Lat Pulldown',         'Back',      'Band',       'banded',     ARRAY['lats'], 132),

-- Chest (continuing 210+)
('incline-dumbbell-fly',         'Incline Dumbbell Fly',        'Chest',     'Dumbbell',   'weighted',   ARRAY['upper chest'], 210),
('decline-dumbbell-press',       'Decline Dumbbell Press',      'Chest',     'Dumbbell',   'weighted',   ARRAY['lower chest'], 211),
('dumbbell-pullover',            'Dumbbell Pullover',           'Chest',     'Dumbbell',   'weighted',   ARRAY['chest','lats'], 212),
('svend-press',                  'Svend Press',                 'Chest',     'Dumbbell',   'weighted',   ARRAY['chest'], 213),
('single-arm-dumbbell-press',    'Single-Arm Dumbbell Press',   'Chest',     'Dumbbell',   'weighted',   ARRAY['chest','core'], 214),
('machine-chest-press',          'Machine Chest Press',         'Chest',     'Machine',    'weighted',   ARRAY['chest','triceps'], 215),
('smith-machine-bench-press',    'Smith Machine Bench Press',   'Chest',     'Machine',    'weighted',   ARRAY['chest','triceps'], 216),
('incline-cable-fly',            'Incline Cable Fly',           'Chest',     'Cable',      'weighted',   ARRAY['upper chest'], 217),
('low-cable-fly',                'Low Cable Fly',               'Chest',     'Cable',      'weighted',   ARRAY['upper chest'], 218),
('high-cable-fly',               'High Cable Fly',              'Chest',     'Cable',      'weighted',   ARRAY['lower chest'], 219),
('cable-chest-press',            'Cable Chest Press',           'Chest',     'Cable',      'weighted',   ARRAY['chest','triceps'], 220),
('floor-press',                  'Floor Press',                 'Chest',     'Barbell',    'weighted',   ARRAY['chest','triceps'], 221),
('incline-push-up',              'Incline Push-Up',             'Chest',     'Bodyweight', 'bodyweight', ARRAY['chest','triceps'], 222),
('decline-push-up',              'Decline Push-Up',             'Chest',     'Bodyweight', 'bodyweight', ARRAY['upper chest','triceps'], 223),
('diamond-push-up',              'Diamond Push-Up',             'Chest',     'Bodyweight', 'bodyweight', ARRAY['triceps','chest'], 224),
('wide-push-up',                 'Wide Push-Up',                'Chest',     'Bodyweight', 'bodyweight', ARRAY['chest'], 225),
('archer-push-up',               'Archer Push-Up',              'Chest',     'Bodyweight', 'bodyweight', ARRAY['chest','triceps'], 226),
('clap-push-up',                 'Clap Push-Up',                'Chest',     'Bodyweight', 'bodyweight', ARRAY['chest','triceps'], 227),
('weighted-dip',                 'Weighted Dip',                'Chest',     'Bodyweight', 'weighted',   ARRAY['chest','triceps'], 228),
('banded-chest-press',           'Banded Chest Press',          'Chest',     'Band',       'banded',     ARRAY['chest','triceps'], 229),

-- Legs (continuing 315+)
('barbell-lunge',                'Barbell Lunge',               'Legs',      'Barbell',    'weighted',   ARRAY['quads','glutes'], 315),
('dumbbell-lunge',               'Dumbbell Lunge',              'Legs',      'Dumbbell',   'weighted',   ARRAY['quads','glutes'], 316),
('reverse-lunge',                'Reverse Lunge',               'Legs',      'Dumbbell',   'weighted',   ARRAY['quads','glutes'], 317),
('lateral-lunge',                'Lateral Lunge',               'Legs',      'Dumbbell',   'weighted',   ARRAY['adductors','quads'], 318),
('curtsy-lunge',                 'Curtsy Lunge',                'Legs',      'Dumbbell',   'weighted',   ARRAY['glutes','quads'], 319),
('step-up',                      'Step-Up',                     'Legs',      'Dumbbell',   'weighted',   ARRAY['quads','glutes'], 320),
('split-squat',                  'Split Squat',                 'Legs',      'Dumbbell',   'weighted',   ARRAY['quads','glutes'], 321),
('zercher-squat',                'Zercher Squat',               'Legs',      'Barbell',    'weighted',   ARRAY['quads','core'], 322),
('safety-bar-squat',             'Safety Bar Squat',            'Legs',      'Barbell',    'weighted',   ARRAY['quads','glutes'], 323),
('pause-squat',                  'Pause Squat',                 'Legs',      'Barbell',    'weighted',   ARRAY['quads','glutes'], 324),
('belt-squat',                   'Belt Squat',                  'Legs',      'Machine',    'weighted',   ARRAY['quads','glutes'], 325),
('smith-machine-squat',          'Smith Machine Squat',         'Legs',      'Machine',    'weighted',   ARRAY['quads','glutes'], 326),
('sissy-squat',                  'Sissy Squat',                 'Legs',      'Bodyweight', 'bodyweight', ARRAY['quads'], 327),
('bodyweight-squat',             'Bodyweight Squat',            'Legs',      'Bodyweight', 'bodyweight', ARRAY['quads','glutes'], 328),
('jump-squat',                   'Jump Squat',                  'Legs',      'Bodyweight', 'bodyweight', ARRAY['quads','glutes'], 329),
('pistol-squat',                 'Pistol Squat',                'Legs',      'Bodyweight', 'bodyweight', ARRAY['quads','glutes'], 330),
('cossack-squat',                'Cossack Squat',               'Legs',      'Bodyweight', 'bodyweight', ARRAY['adductors','quads'], 331),
('wall-sit',                     'Wall Sit',                    'Legs',      'Bodyweight', 'timed',      ARRAY['quads'], 332),
('box-jump',                     'Box Jump',                    'Legs',      'Bodyweight', 'bodyweight', ARRAY['quads','glutes'], 333),
('nordic-curl',                  'Nordic Curl',                 'Legs',      'Bodyweight', 'bodyweight', ARRAY['hamstrings'], 334),
('single-leg-rdl',               'Single-Leg RDL',              'Legs',      'Dumbbell',   'weighted',   ARRAY['hamstrings','glutes'], 335),
('dumbbell-romanian-deadlift',   'Dumbbell Romanian Deadlift',  'Legs',      'Dumbbell',   'weighted',   ARRAY['hamstrings','glutes'], 336),
('single-leg-press',             'Single-Leg Press',            'Legs',      'Machine',    'weighted',   ARRAY['quads','glutes'], 337),
('single-leg-glute-bridge',      'Single-Leg Glute Bridge',     'Legs',      'Bodyweight', 'bodyweight', ARRAY['glutes'], 338),
('cable-kickback',               'Cable Kickback',              'Legs',      'Cable',      'weighted',   ARRAY['glutes'], 339),
('hip-abduction',                'Hip Abduction',               'Legs',      'Machine',    'weighted',   ARRAY['glutes','abductors'], 340),
('hip-adduction',                'Hip Adduction',               'Legs',      'Machine',    'weighted',   ARRAY['adductors'], 341),
('donkey-calf-raise',            'Donkey Calf Raise',           'Legs',      'Machine',    'weighted',   ARRAY['calves'], 342),
('single-leg-calf-raise',        'Single-Leg Calf Raise',       'Legs',      'Bodyweight', 'bodyweight', ARRAY['calves'], 343),
('tibialis-raise',               'Tibialis Raise',              'Legs',      'Bodyweight', 'bodyweight', ARRAY['tibialis'], 344),
('kettlebell-goblet-squat',      'Kettlebell Goblet Squat',     'Legs',      'Kettlebell', 'weighted',   ARRAY['quads','glutes'], 345),
('kettlebell-deadlift',          'Kettlebell Deadlift',         'Legs',      'Kettlebell', 'weighted',   ARRAY['glutes','hamstrings'], 346),
('kettlebell-single-leg-deadlift', 'Kettlebell Single-Leg Deadlift', 'Legs', 'Kettlebell', 'weighted',   ARRAY['hamstrings','glutes'], 347),
('banded-squat',                 'Banded Squat',                'Legs',      'Band',       'banded',     ARRAY['quads','glutes'], 348),
('banded-glute-bridge',          'Banded Glute Bridge',         'Legs',      'Band',       'banded',     ARRAY['glutes'], 349),
('lateral-band-walk',            'Lateral Band Walk',           'Legs',      'Band',       'banded',     ARRAY['glutes','abductors'], 350),
('monster-walk',                 'Monster Walk',                'Legs',      'Band',       'banded',     ARRAY['glutes'], 351),

-- Shoulders (continuing 408+)
('seated-barbell-press',         'Seated Barbell Press',        'Shoulders', 'Barbell',    'weighted',   ARRAY['front delts','triceps'], 408),
('standing-dumbbell-press',      'Standing Dumbbell Press',     'Shoulders', 'Dumbbell',   'weighted',   ARRAY['front delts','side delts'], 409),
('single-arm-overhead-press',    'Single-Arm Overhead Press',   'Shoulders', 'Dumbbell',   'weighted',   ARRAY['front delts','core'], 410),
('machine-shoulder-press',       'Machine Shoulder Press',      'Shoulders', 'Machine',    'weighted',   ARRAY['front delts'], 411),
('smith-machine-shoulder-press', 'Smith Machine Shoulder Press','Shoulders', 'Machine',    'weighted',   ARRAY['front delts','triceps'], 412),
('z-press',                      'Z Press',                     'Shoulders', 'Barbell',    'weighted',   ARRAY['front delts','core'], 413),
('front-raise',                  'Front Raise',                 'Shoulders', 'Dumbbell',   'weighted',   ARRAY['front delts'], 414),
('cable-front-raise',            'Cable Front Raise',           'Shoulders', 'Cable',      'weighted',   ARRAY['front delts'], 415),
('plate-front-raise',            'Plate Front Raise',           'Shoulders', 'Barbell',    'weighted',   ARRAY['front delts'], 416),
('bent-over-lateral-raise',      'Bent-Over Lateral Raise',     'Shoulders', 'Dumbbell',   'weighted',   ARRAY['rear delts'], 417),
('reverse-pec-deck',             'Reverse Pec Deck',            'Shoulders', 'Machine',    'weighted',   ARRAY['rear delts'], 418),
('cable-rear-delt-fly',          'Cable Rear Delt Fly',         'Shoulders', 'Cable',      'weighted',   ARRAY['rear delts'], 419),
('seesaw-press',                 'Seesaw Press',                'Shoulders', 'Dumbbell',   'weighted',   ARRAY['front delts','core'], 420),
('handstand-push-up',            'Handstand Push-Up',           'Shoulders', 'Bodyweight', 'bodyweight', ARRAY['front delts','triceps'], 421),
('pike-push-up',                 'Pike Push-Up',                'Shoulders', 'Bodyweight', 'bodyweight', ARRAY['front delts','triceps'], 422),
('kettlebell-press',             'Kettlebell Press',            'Shoulders', 'Kettlebell', 'weighted',   ARRAY['front delts','triceps'], 423),
('kettlebell-bottoms-up-press',  'Kettlebell Bottoms-Up Press', 'Shoulders', 'Kettlebell', 'weighted',   ARRAY['front delts','core'], 424),
('banded-overhead-press',        'Banded Overhead Press',       'Shoulders', 'Band',       'banded',     ARRAY['front delts','triceps'], 425),
('banded-lateral-raise',         'Banded Lateral Raise',        'Shoulders', 'Band',       'banded',     ARRAY['side delts'], 426),

-- Arms (continuing 509+)
('spider-curl',                  'Spider Curl',                 'Arms',      'Dumbbell',   'weighted',   ARRAY['biceps'], 509),
('concentration-curl',           'Concentration Curl',          'Arms',      'Dumbbell',   'weighted',   ARRAY['biceps'], 510),
('incline-dumbbell-curl',        'Incline Dumbbell Curl',       'Arms',      'Dumbbell',   'weighted',   ARRAY['biceps'], 511),
('zottman-curl',                 'Zottman Curl',                'Arms',      'Dumbbell',   'weighted',   ARRAY['biceps','forearms'], 512),
('cable-curl',                   'Cable Curl',                  'Arms',      'Cable',      'weighted',   ARRAY['biceps'], 513),
('rope-hammer-curl',             'Rope Hammer Curl',            'Arms',      'Cable',      'weighted',   ARRAY['biceps','forearms'], 514),
('drag-curl',                    'Drag Curl',                   'Arms',      'Barbell',    'weighted',   ARRAY['biceps'], 515),
('reverse-curl',                 'Reverse Curl',                'Arms',      'Barbell',    'weighted',   ARRAY['forearms','biceps'], 516),
('21s',                          '21s',                         'Arms',      'Barbell',    'weighted',   ARRAY['biceps'], 517),
('cheat-curl',                   'Cheat Curl',                  'Arms',      'Barbell',    'weighted',   ARRAY['biceps'], 518),
('rope-tricep-pushdown',         'Rope Tricep Pushdown',        'Arms',      'Cable',      'weighted',   ARRAY['triceps'], 519),
('single-arm-tricep-pushdown',   'Single-Arm Tricep Pushdown',  'Arms',      'Cable',      'weighted',   ARRAY['triceps'], 520),
('overhead-cable-extension',     'Overhead Cable Extension',    'Arms',      'Cable',      'weighted',   ARRAY['triceps'], 521),
('lying-tricep-extension',       'Lying Tricep Extension',      'Arms',      'Dumbbell',   'weighted',   ARRAY['triceps'], 522),
('jm-press',                     'JM Press',                    'Arms',      'Barbell',    'weighted',   ARRAY['triceps'], 523),
('tate-press',                   'Tate Press',                  'Arms',      'Dumbbell',   'weighted',   ARRAY['triceps'], 524),
('bench-dip',                    'Bench Dip',                   'Arms',      'Bodyweight', 'bodyweight', ARRAY['triceps'], 525),
('wrist-curl',                   'Wrist Curl',                  'Arms',      'Dumbbell',   'weighted',   ARRAY['forearms'], 526),
('reverse-wrist-curl',           'Reverse Wrist Curl',          'Arms',      'Dumbbell',   'weighted',   ARRAY['forearms'], 527),
('farmer-carry',                 'Farmer Carry',                'Arms',      'Dumbbell',   'weighted',   ARRAY['forearms','core'], 528),
('banded-curl',                  'Banded Curl',                 'Arms',      'Band',       'banded',     ARRAY['biceps'], 529),
('banded-tricep-pushdown',       'Banded Tricep Pushdown',      'Arms',      'Band',       'banded',     ARRAY['triceps'], 530),
('kettlebell-curl',              'Kettlebell Curl',             'Arms',      'Kettlebell', 'weighted',   ARRAY['biceps'], 531),

-- Core (continuing 606+)
('dead-bug',                     'Dead Bug',                    'Core',      'Bodyweight', 'bodyweight', ARRAY['core'], 606),
('bird-dog',                     'Bird Dog',                    'Core',      'Bodyweight', 'bodyweight', ARRAY['core','glutes'], 607),
('hollow-hold',                  'Hollow Hold',                 'Core',      'Bodyweight', 'timed',      ARRAY['core'], 608),
('v-up',                         'V-Up',                        'Core',      'Bodyweight', 'bodyweight', ARRAY['abs'], 609),
('crunch',                       'Crunch',                      'Core',      'Bodyweight', 'bodyweight', ARRAY['abs'], 610),
('reverse-crunch',               'Reverse Crunch',              'Core',      'Bodyweight', 'bodyweight', ARRAY['abs'], 611),
('bicycle-crunch',               'Bicycle Crunch',              'Core',      'Bodyweight', 'bodyweight', ARRAY['abs','obliques'], 612),
('mountain-climber',             'Mountain Climber',            'Core',      'Bodyweight', 'bodyweight', ARRAY['core','hip flexors'], 613),
('flutter-kick',                 'Flutter Kick',                'Core',      'Bodyweight', 'bodyweight', ARRAY['abs','hip flexors'], 614),
('toe-touch',                    'Toe Touch',                   'Core',      'Bodyweight', 'bodyweight', ARRAY['abs'], 615),
('l-sit',                        'L-Sit',                       'Core',      'Bodyweight', 'timed',      ARRAY['core','hip flexors'], 616),
('dragon-flag',                  'Dragon Flag',                 'Core',      'Bodyweight', 'bodyweight', ARRAY['abs','core'], 617),
('plank-shoulder-tap',           'Plank Shoulder Tap',          'Core',      'Bodyweight', 'bodyweight', ARRAY['core'], 618),
('side-plank-hip-raise',         'Side Plank Hip Raise',        'Core',      'Bodyweight', 'bodyweight', ARRAY['obliques'], 619),
('hanging-knee-raise',           'Hanging Knee Raise',          'Core',      'Bodyweight', 'bodyweight', ARRAY['abs','hip flexors'], 620),
('toes-to-bar',                  'Toes to Bar',                 'Core',      'Bodyweight', 'bodyweight', ARRAY['abs'], 621),
('weighted-sit-up',              'Weighted Sit-Up',             'Core',      'Dumbbell',   'weighted',   ARRAY['abs'], 622),
('decline-sit-up',               'Decline Sit-Up',              'Core',      'Bodyweight', 'bodyweight', ARRAY['abs'], 623),
('seated-russian-twist',         'Seated Russian Twist',        'Core',      'Dumbbell',   'weighted',   ARRAY['obliques'], 624),
('pallof-press',                 'Pallof Press',                'Core',      'Cable',      'weighted',   ARRAY['core','obliques'], 625),
('banded-pallof-press',          'Banded Pallof Press',         'Core',      'Band',       'banded',     ARRAY['core','obliques'], 626),
('cable-woodchopper',            'Cable Woodchopper',           'Core',      'Cable',      'weighted',   ARRAY['obliques','core'], 627),
('landmine-rotation',            'Landmine Rotation',           'Core',      'Barbell',    'weighted',   ARRAY['obliques','core'], 628),
('turkish-get-up',               'Turkish Get-Up',              'Core',      'Kettlebell', 'weighted',   ARRAY['core','full body'], 629),
('kettlebell-windmill',          'Kettlebell Windmill',         'Core',      'Kettlebell', 'weighted',   ARRAY['obliques','core'], 630),
('kettlebell-halo',              'Kettlebell Halo',             'Core',      'Kettlebell', 'weighted',   ARRAY['shoulders','core'], 631),

-- Full Body / Power / Conditioning (continuing 705+)
('thruster',                     'Thruster',                    'Full Body', 'Barbell',    'weighted',   ARRAY['full body'], 705),
('dumbbell-thruster',            'Dumbbell Thruster',           'Full Body', 'Dumbbell',   'weighted',   ARRAY['full body'], 706),
('kettlebell-thruster',          'Kettlebell Thruster',         'Full Body', 'Kettlebell', 'weighted',   ARRAY['full body'], 707),
('man-maker',                    'Man Maker',                   'Full Body', 'Dumbbell',   'weighted',   ARRAY['full body'], 708),
('burpee',                       'Burpee',                      'Full Body', 'Bodyweight', 'bodyweight', ARRAY['full body'], 709),
('kettlebell-swing',             'Kettlebell Swing',            'Full Body', 'Kettlebell', 'weighted',   ARRAY['glutes','back','core'], 710),
('one-arm-kettlebell-swing',     'One-Arm Kettlebell Swing',    'Full Body', 'Kettlebell', 'weighted',   ARRAY['glutes','back','core'], 711),
('kettlebell-snatch',            'Kettlebell Snatch',           'Full Body', 'Kettlebell', 'weighted',   ARRAY['full body'], 712),
('kettlebell-clean',             'Kettlebell Clean',            'Full Body', 'Kettlebell', 'weighted',   ARRAY['back','glutes','shoulders'], 713),
('kettlebell-clean-and-press',   'Kettlebell Clean and Press',  'Full Body', 'Kettlebell', 'weighted',   ARRAY['full body'], 714),
('clean-pull',                   'Clean Pull',                  'Full Body', 'Barbell',    'weighted',   ARRAY['back','traps'], 715),
('high-pull',                    'High Pull',                   'Full Body', 'Barbell',    'weighted',   ARRAY['back','traps','shoulders'], 716),
('muscle-snatch',                'Muscle Snatch',               'Full Body', 'Barbell',    'weighted',   ARRAY['shoulders','back'], 717),
('jerk',                         'Jerk',                        'Full Body', 'Barbell',    'weighted',   ARRAY['shoulders','legs'], 718),
('split-jerk',                   'Split Jerk',                  'Full Body', 'Barbell',    'weighted',   ARRAY['shoulders','legs'], 719),
('sled-push',                    'Sled Push',                   'Full Body', 'Machine',    'cardio-drill', ARRAY['legs','core'], 720),
('sled-pull',                    'Sled Pull',                   'Full Body', 'Machine',    'cardio-drill', ARRAY['back','legs'], 721),
('suitcase-carry',               'Suitcase Carry',              'Full Body', 'Dumbbell',   'weighted',   ARRAY['core','forearms'], 722),
('zercher-carry',                'Zercher Carry',               'Full Body', 'Barbell',    'weighted',   ARRAY['core','biceps'], 723),
('rope-climb',                   'Rope Climb',                  'Full Body', 'Bodyweight', 'bodyweight', ARRAY['lats','core'], 724),
('bear-crawl',                   'Bear Crawl',                  'Full Body', 'Bodyweight', 'cardio-drill', ARRAY['core','shoulders'], 725),
('inchworm',                     'Inchworm',                    'Full Body', 'Bodyweight', 'bodyweight', ARRAY['core','shoulders'], 726),
('wall-ball',                    'Wall Ball',                   'Full Body', 'Dumbbell',   'weighted',   ARRAY['legs','shoulders'], 727);
