import React, { useState } from 'react';
import { C, S, F } from '../lib/theme.js';
import { Icon } from '../lib/icons.js';
import { SPORT_META } from '../lib/constants.js';

export const Card=({children,style,onClick,accent})=>(<div onClick={onClick} style={{background:accent?accent+'08':C.card,border:`1.5px solid ${accent?accent+'30':C.border}`,borderRadius:16,padding:'16px 18px',cursor:onClick?'pointer':'default',transition:'all .18s',boxShadow:S.card,overflow:'hidden',...style}} onMouseEnter={e=>{if(onClick){e.currentTarget.style.boxShadow=S.md;e.currentTarget.style.transform='translateY(-1px)';e.currentTarget.style.borderColor=accent?accent+'55':C.borderBright;}}} onMouseLeave={e=>{if(onClick){e.currentTarget.style.boxShadow=S.card;e.currentTarget.style.transform='none';e.currentTarget.style.borderColor=accent?accent+'30':C.border;}}}>{children}</div>);
export const Label=({children,style})=><div style={{fontFamily:F.ui,fontSize:12,fontWeight:600,color:C.muted,textTransform:'uppercase',letterSpacing:'.08em',marginBottom:10,...style}}>{children}</div>;
export const Pill=({children,color,small})=><span style={{display:'inline-flex',alignItems:'center',gap:4,background:(color||C.accent)+'15',color:color||C.accent,borderRadius:20,padding:small?'3px 10px':'4px 12px',fontFamily:F.ui,fontSize:small?11:12,fontWeight:600,whiteSpace:'nowrap'}}>{children}</span>;
export const SportBadge=({sport,small})=>{const s=SPORT_META[sport]||SPORT_META.other;return (<span style={{display:'inline-flex',alignItems:'center',gap:4,background:s.color+'15',color:s.color,borderRadius:20,padding:small?'3px 10px':'4px 12px',fontFamily:F.ui,fontSize:small?11:12,fontWeight:600,whiteSpace:'nowrap'}}><Icon name={s.icon} size={small?11:13} color={s.color}/>{s.label}</span>);};
export const Inp=React.forwardRef(({style,...props}, ref)=><input ref={ref} style={{background:C.elevated,border:`1.5px solid ${C.border}`,borderRadius:12,padding:'13px 16px',color:C.text,fontFamily:F.ui,fontSize:15,outline:'none',width:'100%',boxSizing:'border-box',transition:'all .15s',...style}} onFocus={e=>{e.target.style.borderColor=C.accent;e.target.style.background=C.surface;}} onBlur={e=>{e.target.style.borderColor=C.border;e.target.style.background=C.elevated;}} {...props}/>);
export const Btn=({children,onClick,color,outline,style,disabled})=><button onClick={onClick} disabled={disabled} style={{background:outline?'transparent':(disabled?C.elevated:(color||C.accent)),border:`1.5px solid ${outline?C.border:(disabled?C.elevated:(color||C.accent))}`,borderRadius:14,padding:'13px 22px',color:disabled?C.muted:(outline?C.subtle:'#fff'),fontFamily:F.display,fontSize:16,fontWeight:700,cursor:disabled?'not-allowed':'pointer',transition:'all .15s',...style}}>{children}</button>;
export const DotsLoader=({color})=><div style={{display:'flex',gap:5,padding:'4px 0'}}>{[0,1,2].map(n=><div key={n} style={{width:7,height:7,borderRadius:'50%',background:color||C.muted,animation:`blink 1.3s ease-in-out ${n*.22}s infinite`}}/>)}</div>;
export const Spinner=({color,size=16})=><div style={{width:size,height:size,borderRadius:'50%',border:`2px solid ${(color||C.accent)}30`,borderTop:`2px solid ${color||C.accent}`,animation:'spin .8s linear infinite'}}/>;
export const Textarea=({style,...props})=><textarea style={{background:C.elevated,border:`1.5px solid ${C.border}`,borderRadius:12,padding:'13px 16px',color:C.text,fontFamily:F.ui,fontSize:15,outline:'none',width:'100%',resize:'none',lineHeight:1.7,transition:'all .15s',...style}} onFocus={e=>{e.target.style.borderColor=C.accent;e.target.style.background=C.surface;}} onBlur={e=>{e.target.style.borderColor=C.border;e.target.style.background=C.elevated;}} {...props}/>;
export const Sheet=({children,onClose,title})=>(<div style={{position:'fixed',inset:0,background:'rgba(28,27,46,.35)',zIndex:200,display:'flex',alignItems:'flex-end',justifyContent:'center',backdropFilter:'blur(3px)'}} onClick={onClose}><div onClick={e=>e.stopPropagation()} className="fade-up" style={{background:C.surface,borderRadius:'24px 24px 0 0',width:'100%',maxWidth:500,padding:'24px 20px 52px',maxHeight:'92vh',overflowY:'auto',boxShadow:'0 -4px 32px rgba(28,27,46,.12)'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:20}}><div style={{fontFamily:F.display,fontSize:22,fontWeight:800,color:C.text,letterSpacing:'-.01em'}}>{title}</div><button onClick={onClose} style={{width:32,height:32,borderRadius:10,background:C.elevated,border:'none',color:C.subtle,fontSize:16,cursor:'pointer',display:'flex',alignItems:'center',justifyContent:'center'}}>✕</button></div>{children}</div></div>);

export function Toggle({ on, onToggle }) {
  return (
    <div onClick={onToggle} style={{width:50,height:28,borderRadius:14,background:on?C.accent:C.border,position:'relative',cursor:'pointer',transition:'background .25s',flexShrink:0}}>
      <div style={{position:'absolute',top:3,left:on?25:3,width:22,height:22,borderRadius:'50%',background:'#fff',transition:'left .25s cubic-bezier(.4,0,.2,1)',boxShadow:'0 1px 4px rgba(0,0,0,.28)'}}/>
    </div>
  );
}
